***************
*** 1,8 ****
  VERSION = 3
- PATCHLEVEL = 5
  SUBLEVEL = 0
  EXTRAVERSION =
- NAME = Saber-toothed Squirrel
  
  # *DOCUMENTATION*
  # To see a list of typical targets execute "make help"
--- 1,8 ----
  VERSION = 3
+ PATCHLEVEL = 6
  SUBLEVEL = 0
  EXTRAVERSION =
+ NAME = Terrified Chipmunk
  
  # *DOCUMENTATION*
  # To see a list of typical targets execute "make help"
