***************
*** 15,22 ****
  obj-$(CONFIG_ARCH_USES_GETTIMEOFFSET)   += time.o
  obj-$(CONFIG_S5P_HRT) 		+= s5p-time.o
  
- obj-y				+= clock.o
- obj-y				+= pwm-clock.o
  
  obj-$(CONFIG_SAMSUNG_CLKSRC)	+= clock-clksrc.o
  obj-$(CONFIG_S5P_CLOCK)		+= s5p-clock.o
--- 15,22 ----
  obj-$(CONFIG_ARCH_USES_GETTIMEOFFSET)   += time.o
  obj-$(CONFIG_S5P_HRT) 		+= s5p-time.o
  
+ obj-$(CONFIG_SAMSUNG_CLOCK)	+= clock.o
+ obj-$(CONFIG_SAMSUNG_CLOCK)	+= pwm-clock.o
  
  obj-$(CONFIG_SAMSUNG_CLKSRC)	+= clock-clksrc.o
  obj-$(CONFIG_S5P_CLOCK)		+= s5p-clock.o
***************
*** 59,69 ****
  
  obj-$(CONFIG_S5P_PM)		+= s5p-pm.o s5p-irq-pm.o
  obj-$(CONFIG_S5P_SLEEP)		+= s5p-sleep.o
- 
- # PD support
- 
- obj-$(CONFIG_SAMSUNG_PD)	+= pd.o
- 
- # PWM support
- 
- obj-$(CONFIG_HAVE_PWM)		+= pwm.o
--- 59,61 ----
  
  obj-$(CONFIG_S5P_PM)		+= s5p-pm.o s5p-irq-pm.o
  obj-$(CONFIG_S5P_SLEEP)		+= s5p-sleep.o
