***************
*** 3,5 ****
  #
  
  obj-y += cpuidle.o driver.o governor.o sysfs.o governors/
--- 3,6 ----
  #
  
  obj-y += cpuidle.o driver.o governor.o sysfs.o governors/
+ obj-$(CONFIG_ARCH_NEEDS_CPU_IDLE_COUPLED) += coupled.o
